import { useQuery } from '@tanstack/react-query'
import { Link, Route, Routes, useNavigate } from 'react-router-dom'
import { api } from './lib/api'
import { GlassSurface, LargeTitleHeader, ListGroup, ListRow, PressableButton, SegmentedControl, Toggle, WidgetGrid } from './components/ios'
import { useState } from 'react'
import { CommandPalette } from './components/CommandPalette'

function Home() {
  const status = useQuery({ queryKey: ['status'], queryFn: () => api<{ bot: { online: boolean } }>('/status') })
  const navigate = useNavigate()
  return <main className="app"><h1>Zephyr</h1><p>A weather-first Discord companion.</p><p>{status.isPending ? 'Connecting…' : status.data?.bot.online ? 'Bot online' : 'Bot offline'}</p><PressableButton onClick={() => navigate('/weather')}>Weather</PressableButton> <Link to="/kitchen-sink">Design system</Link></main>
}
type Place = { name: string; country?: string; latitude: number; longitude: number }
type Weather = { current: { temperature: number | null; feels_like: number | null; description: string; icon: string }; daily: Array<{ time_local: string; temp_max: number; temp_min: number; description: string }>; air_quality: { european_band: string } | null }
function WeatherPage() { const [query, setQuery] = useState('Iloilo City'); const [place, setPlace] = useState<Place | null>(null); const places = useQuery({ queryKey:['geocode',query], queryFn: () => api<{results: Place[]}>(`/geocode?q=${encodeURIComponent(query)}`), enabled: query.length >= 2 }); const weather = useQuery({ queryKey:['weather',place], queryFn: () => api<Weather>(`/weather?lat=${place!.latitude}&lon=${place!.longitude}`), enabled: !!place }); return <main className="app"><LargeTitleHeader title="Weather" /><input aria-label="Search city" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search city" />{!place && <ListGroup>{places.data?.results.map(result => <ListRow key={`${result.latitude}:${result.longitude}`} label={`${result.name}${result.country ? `, ${result.country}` : ''}`}><PressableButton onClick={() => setPlace(result)}>Use</PressableButton></ListRow>)}</ListGroup>}{weather.data && <><GlassSurface><h2>{place?.name ?? 'Current Location'}</h2><p>{weather.data.current.temperature}° · {weather.data.current.description}</p><small>Feels like {weather.data.current.feels_like}°</small></GlassSurface><WidgetGrid>{weather.data.daily.map(day => <GlassSurface key={day.time_local}><b>{day.time_local}</b><p>{day.temp_max}° / {day.temp_min}°</p><small>{day.description}</small></GlassSurface>)}</WidgetGrid></>}<p><Link to="/">Back</Link></p></main> }
function KitchenSink() { const [selected, setSelected] = useState('Today'); const [enabled, setEnabled] = useState(true); return <main className="app"><LargeTitleHeader title="Kitchen Sink" /><SegmentedControl values={['Today','Tomorrow']} value={selected} onChange={setSelected} /><WidgetGrid><GlassSurface><h2>Weather</h2><p>26° • Partly cloudy</p></GlassSurface><GlassSurface><h2>Air quality</h2><p>Good</p></GlassSurface></WidgetGrid><ListGroup><ListRow label="Dark appearance"><Toggle checked={enabled} onChange={setEnabled} /></ListRow></ListGroup><p><PressableButton onClick={() => document.documentElement.classList.toggle('dark')}>Toggle theme</PressableButton></p><Link to="/">Back</Link></main> }
export default function App() { return <><Routes><Route path="/" element={<Home />} /><Route path="/weather" element={<WeatherPage />} /><Route path="/kitchen-sink" element={<KitchenSink />} /><Route path="*" element={<Home />} /></Routes><CommandPalette /></> }
