import { useDeferredValue, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../lib/api'
import { useLogout, useMe } from '../lib/auth'
import { haptic } from '../lib/haptics'
import { PINS_KEY, RECENTS_KEY, readIds, writeIds, type GuildCategory, type GuildSort } from '../lib/preferences'
import { useTheme } from '../lib/theme-context'
import { GuildIcon, UserAvatar } from '../components/DiscordAvatar'
import { Chevron, GlassSurface, PressableButton, SectionLabel, SegmentedControl, WidgetGrid } from '../components/ios'
import type { MeGuild } from '../types/api'

type Status = { bot: { online: boolean; guild_count: number | null; latency_ms: number | null; uptime_s: number | null } }
const categoryLabels: Record<GuildCategory, string> = { all: 'All', pinned: 'Pinned', installed: 'Installed', 'needs-bot': 'Needs Zephyr', unknown: 'Unknown' }
const sortLabels: Record<GuildSort, string> = { pinned: 'Pinned first', recent: 'Recently opened', 'name-asc': 'Name A–Z', 'name-desc': 'Name Z–A', status: 'Bot status' }
function presence(botPresent: boolean | null) { return botPresent === null ? { text: 'Bot status unknown', tone: 'unknown' } : botPresent ? { text: 'Zephyr is in this server', tone: 'ok' } : { text: 'Zephyr is not in this server yet', tone: 'off' } }
function formatUptime(seconds: number | null | undefined) { if (seconds == null) return '—'; const days = Math.floor(seconds / 86400), hours = Math.floor(seconds % 86400 / 3600), minutes = Math.floor(seconds % 3600 / 60); return days ? `${days}d ${hours}h` : hours ? `${hours}h ${minutes}m` : `${minutes}m` }
function matchesCategory(guild: MeGuild, category: GuildCategory, pins: string[]) { return category === 'all' || category === 'pinned' && pins.includes(guild.id) || category === 'installed' && guild.bot_present === true || category === 'needs-bot' && guild.bot_present === false || category === 'unknown' && guild.bot_present === null }
function statusOrder(value: boolean | null) { return value === true ? 0 : value === false ? 1 : 2 }

function ServerCard({ guild, pinned, onPin, onVisit }: { guild: MeGuild; pinned: boolean; onPin(): void; onVisit(): void }) {
  const { text, tone } = presence(guild.bot_present)
  return <article className="server-card-wrap"><Link to={`/g/${guild.id}`} onClick={onVisit} className="glass glass-regular glass-interactive server-card" data-glass="1"><GuildIcon name={guild.name} iconUrl={guild.icon_url} /><span className="server-card-body"><b>{guild.name}</b><small><i className={`dot ${tone}`} aria-hidden />{text}</small></span><Chevron /></Link><button type="button" className={`pin-button ${pinned ? 'active' : ''}`} aria-label={`${pinned ? 'Unpin' : 'Pin'} ${guild.name}`} aria-pressed={pinned} onClick={onPin}>★</button></article>
}

export function Guilds() {
  const me = useMe(); const logout = useLogout(); const navigate = useNavigate(); const { preferences, patchPreferences } = useTheme(); const [term, setTerm] = useState(''); const search = useDeferredValue(term); const [pins, setPins] = useState(() => readIds(PINS_KEY)); const [recents, setRecents] = useState(() => readIds(RECENTS_KEY))
  const status = useQuery({ queryKey: ['status'], queryFn: () => api<Status>('/status') }); const { user, guilds, invite_url: inviteUrl, guilds_stale: stale } = me.data!; const bot = status.data?.bot; const name = user.global_name ?? user.username; const present = guilds.filter(guild => guild.bot_present === true).length
  const shown = useMemo(() => guilds.filter(guild => guild.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).filter(guild => matchesCategory(guild, preferences.guildCategory, pins)).sort((a, b) => {
    const alpha = a.name.localeCompare(b.name), pin = Number(pins.includes(b.id)) - Number(pins.includes(a.id)), recent = recents.indexOf(a.id) - recents.indexOf(b.id)
    if (preferences.guildSort === 'name-asc') return alpha; if (preferences.guildSort === 'name-desc') return -alpha; if (preferences.guildSort === 'status') return statusOrder(a.bot_present) - statusOrder(b.bot_present) || alpha; if (preferences.guildSort === 'recent') return (recent < 0 ? Number.MAX_SAFE_INTEGER : recent) - (recents.indexOf(b.id) < 0 ? Number.MAX_SAFE_INTEGER : recents.indexOf(b.id)) || alpha; return pin || alpha
  }), [guilds, search, preferences.guildCategory, preferences.guildSort, pins, recents])
  const togglePin = (id: string) => { const next = pins.includes(id) ? pins.filter(pin => pin !== id) : [...pins, id]; setPins(next); writeIds(PINS_KEY, next) }
  const visit = (id: string) => { const next = [id, ...recents.filter(recent => recent !== id)].slice(0, 12); setRecents(next); writeIds(RECENTS_KEY, next) }
  return <main className="app"><header className="dash-head"><div><h1>Dashboard</h1><p className="subtitle">Welcome back, {name}.</p></div><div className="dash-account"><UserAvatar name={user.username} avatarUrl={user.avatar_url} /><span className="dash-identity"><b>{name}</b><small>@{user.username}</small></span><PressableButton variant="danger" className="small" disabled={logout.isPending} onClick={() => { haptic(15); logout.mutate(undefined, { onSuccess: () => navigate('/login', { replace: true }) }) }}>{logout.isPending ? 'Signing out…' : 'Sign out'}</PressableButton></div></header>
    <WidgetGrid className="dash-stats"><GlassSurface><h2>Zephyr</h2><p className="stat-row"><i className={`dot lg ${status.isPending ? '' : bot?.online ? 'ok' : 'off'}`.trim()} aria-hidden />{status.isPending ? 'Checking…' : bot?.online ? 'Online' : 'Offline'}</p><small className="muted">{bot?.online && bot.latency_ms != null ? `${Math.round(bot.latency_ms)} ms` : 'No heartbeat'}</small></GlassSurface><GlassSurface><h2>You manage</h2><p className="stat-value">{guilds.length}</p><small className="muted">servers</small></GlassSurface><GlassSurface><h2>Zephyr is in</h2><p className="stat-value">{present}<span className="stat-of"> / {guilds.length}</span></p><small className="muted">of your servers</small></GlassSurface><GlassSurface><h2>Uptime</h2><p className="stat-value">{formatUptime(bot?.uptime_s)}</p><small className="muted">{bot?.guild_count != null ? `${bot.guild_count} servers total` : 'Not reporting'}</small></GlassSurface></WidgetGrid>
    {stale && <GlassSurface tier="thin" className="notice"><i className="dot unknown" aria-hidden /><p>Your server list may be out of date. <a href="/api/v1/auth/login?next=%2Fg">Refresh it</a>.</p></GlassSurface>}
    <div className="section-head"><SectionLabel>Your servers <span className="muted">({shown.length})</span></SectionLabel><a className="ios-button secondary small" href={inviteUrl}>Add Zephyr</a></div><div className="server-finder"><div className="search-field"><span className="lens" aria-hidden /><input className="search-input" aria-label="Search servers" value={term} onChange={event => setTerm(event.target.value)} placeholder="Search your servers…" /></div><label className="finder-select">Category<select value={preferences.guildCategory} onChange={event => patchPreferences({ guildCategory: event.target.value as GuildCategory })}>{(Object.keys(categoryLabels) as GuildCategory[]).map(key => <option key={key} value={key}>{categoryLabels[key]}</option>)}</select></label><label className="finder-select">Sort<select value={preferences.guildSort} onChange={event => patchPreferences({ guildSort: event.target.value as GuildSort })}>{(Object.keys(sortLabels) as GuildSort[]).map(key => <option key={key} value={key}>{sortLabels[key]}</option>)}</select></label><SegmentedControl values={['cards', 'list']} labels={{ cards: 'Cards', list: 'List' }} value={preferences.dashboardView} onChange={value => patchPreferences({ dashboardView: value as 'cards' | 'list' })} /></div>
    {shown.length ? <div className={`server-grid ${preferences.dashboardView === 'list' ? 'server-list-view' : ''}`}>{shown.map(guild => <ServerCard key={guild.id} guild={guild} pinned={pins.includes(guild.id)} onPin={() => togglePin(guild.id)} onVisit={() => visit(guild.id)} />)}</div> : <GlassSurface tier="thin"><p>No servers match this search.</p><p className="muted">Try a different category or clear the search.</p></GlassSurface>}</main>
}
