import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import { GlassSurface, LargeTitleHeader, ListGroup, ListRow, PressableButton, WidgetGrid } from '../components/ios'

type Place = { name: string; country?: string; latitude: number; longitude: number }
type Weather = { current: { temperature: number | null; feels_like: number | null; description: string; icon: string }; daily: Array<{ time_local: string; temp_max: number; temp_min: number; description: string }>; air_quality: { european_band: string } | null }
export function Weather() { const [query, setQuery] = useState('Iloilo City'); const [place, setPlace] = useState<Place | null>(null); const places = useQuery({ queryKey:['geocode',query], queryFn: () => api<{results: Place[]}>(`/geocode?q=${encodeURIComponent(query)}`), enabled: query.length >= 2 }); const weather = useQuery({ queryKey:['weather',place], queryFn: () => api<Weather>(`/weather?lat=${place!.latitude}&lon=${place!.longitude}`), enabled: !!place }); return <main className="app"><LargeTitleHeader title="Weather" /><input aria-label="Search city" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search city" />{!place && <ListGroup>{places.data?.results.map(result => <ListRow key={`${result.latitude}:${result.longitude}`} label={`${result.name}${result.country ? `, ${result.country}` : ''}`}><PressableButton onClick={() => setPlace(result)}>Use</PressableButton></ListRow>)}</ListGroup>}{weather.data && <><GlassSurface><h2>{place?.name ?? 'Current Location'}</h2><p>{weather.data.current.temperature}° · {weather.data.current.description}</p><small>Feels like {weather.data.current.feels_like}°</small></GlassSurface><WidgetGrid>{weather.data.daily.map(day => <GlassSurface key={day.time_local}><b>{day.time_local}</b><p>{day.temp_max}° / {day.temp_min}°</p><small>{day.description}</small></GlassSurface>)}</WidgetGrid></>}<p><Link to="/">Back</Link></p></main> }
